name: Deploy staging
on:
  [push, fork]

env:
  GITHUB_USER: AifoSca

jobs:
  deploy:
    name: Build and deploy latest image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        run: echo "::set-output name=VERSION::$(git rev-parse --short HEAD)"
        id: version
      - name: Change terragrunt file
        run: |
          find ./terragrunt -name '*.hcl' -exec sed -i 's/image = "alpine:[a-z0-9]*/image = "alpine:${{ steps.version.outputs.VERSION }}/g' {} \;
      - name: Commit and push changes
        run: |
          git config --global user.name "AifoSca"
          git add -A
          git commit -m "commit message"
          git push
